const _ = require('lodash');
const states = [
  { name: "Alabama	", abbr: "AL" },
  { name: "Montana	", abbr: "MT" },
  { name: "Alaska	", abbr: "AK" },
  { name: "Nebraska	", abbr: "NE" },
  { name: "Arizona	", abbr: "AZ" },
  { name: "Nevada	", abbr: "NV" },
  { name: "Arkansas	", abbr: "AR" },
  { name: "New Hampshire	", abbr: "NH" },
  { name: "California	", abbr: "CA" },
  { name: "New Jersey	", abbr: "NJ" },
  { name: "Colorado	", abbr: "CO" },
  { name: "New Mexico	", abbr: "NM" },
  { name: "Connecticut	", abbr: "CT" },
  { name: "New York	", abbr: "NY" },
  { name: "Delaware	", abbr: "DE" },
  { name: "North Carolina	", abbr: "NC" },
  { name: "Florida	", abbr: "FL" },
  { name: "North Dakota	", abbr: "ND" },
  { name: "Georgia	", abbr: "GA" },
  { name: "Ohio	", abbr: "OH" },
  { name: "Hawaii	", abbr: "HI" },
  { name: "Oklahoma	", abbr: "OK" },
  { name: "Idaho	", abbr: "ID" },
  { name: "Oregon	", abbr: "OR" },
  { name: "Illinois	", abbr: "IL" },
  { name: "Pennsylvania	", abbr: "PA" },
  { name: "Indiana	", abbr: "IN" },
  { name: "Rhode Island	", abbr: "RI" },
  { name: "Iowa	", abbr: "IA" },
  { name: "South Carolina	", abbr: "SC" },
  { name: "Kansas	", abbr: "KS" },
  { name: "South Dakota	", abbr: "SD" },
  { name: "Kentucky	", abbr: "KY" },
  { name: "Tennessee	", abbr: "TN" },
  { name: "Louisiana	", abbr: "LA" },
  { name: "Texas	", abbr: "TX" },
  { name: "Maine	", abbr: "ME" },
  { name: "Utah	", abbr: "UT" },
  { name: "Maryland	", abbr: "MD" },
  { name: "Vermont	", abbr: "VT" },
  { name: "Massachusetts	", abbr: "MA" },
  { name: "Virginia	", abbr: "VA" },
  { name: "Michigan	", abbr: "MI" },
  { name: "Washington	", abbr: "WA" },
  { name: "Minnesota	", abbr: "MN" },
  { name: "West Virginia	", abbr: "WV" },
  { name: "Mississippi	", abbr: "MS" },
  { name: "Wisconsin	", abbr: "WI" },
  { name: "Missouri	", abbr: "MO" },
  { name: "Wyoming	", abbr: "WY" }
];

module.exports = function (abbr) {
  let idx = _.random(0, states.length - 1);
  let def = states[idx];
  return abbr ? def.abbr : def.name;
};